 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fan_comments", type: :request do
  # FanComment. As you add validations to FanComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FanComment.create! valid_attributes
      get fan_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fan_comment = FanComment.create! valid_attributes
      get fan_comment_url(fan_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fan_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      fan_comment = FanComment.create! valid_attributes
      get edit_fan_comment_url(fan_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FanComment" do
        expect {
          post fan_comments_url, params: { fan_comment: valid_attributes }
        }.to change(FanComment, :count).by(1)
      end

      it "redirects to the created fan_comment" do
        post fan_comments_url, params: { fan_comment: valid_attributes }
        expect(response).to redirect_to(fan_comment_url(FanComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FanComment" do
        expect {
          post fan_comments_url, params: { fan_comment: invalid_attributes }
        }.to change(FanComment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post fan_comments_url, params: { fan_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fan_comment" do
        fan_comment = FanComment.create! valid_attributes
        patch fan_comment_url(fan_comment), params: { fan_comment: new_attributes }
        fan_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fan_comment" do
        fan_comment = FanComment.create! valid_attributes
        patch fan_comment_url(fan_comment), params: { fan_comment: new_attributes }
        fan_comment.reload
        expect(response).to redirect_to(fan_comment_url(fan_comment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        fan_comment = FanComment.create! valid_attributes
        patch fan_comment_url(fan_comment), params: { fan_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fan_comment" do
      fan_comment = FanComment.create! valid_attributes
      expect {
        delete fan_comment_url(fan_comment)
      }.to change(FanComment, :count).by(-1)
    end

    it "redirects to the fan_comments list" do
      fan_comment = FanComment.create! valid_attributes
      delete fan_comment_url(fan_comment)
      expect(response).to redirect_to(fan_comments_url)
    end
  end
end
